In [1]:
!git clone https://github.com/ChrisWu1997/DeepCAD.git

Cloning into 'DeepCAD'...
remote: Enumerating objects: 112, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 112 (delta 33), reused 76 (delta 29), pack-reused 12 (from 1)
Receiving objects: 100% (112/112), 253.97 KiB | 8.76 MiB/s, done.
Resolving deltas: 100% (33/33), done.


In [3]:
!cd DeepCAD

In [5]:
!pip install -r DeepCAD/requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 35.0 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ...   error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [12]:
import torch
k = torch.ones(5,6, 3)
print(k)
t = torch.zeros(5,1, 3)
print(t)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]]])


In [11]:
size = t.size()[1:]
print(size)

torch.Size([3])


In [14]:
c =torch.cat((k, t), dim=1)
print(c)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]]])


In [21]:
a, = [[1, 2, 3]]

In [22]:
a

[1, 2, 3]

In [34]:
r = torch.randn(5,  3)>0
print(r)
print(r.cumsum(1))

tensor([[ True, False,  True],
        [ True, False,  True],
        [ True,  True, False],
        [ True, False, False],
        [False, False,  True]])
tensor([[1, 1, 2],
        [1, 1, 2],
        [1, 2, 2],
        [1, 1, 1],
        [0, 0, 1]])


In [ ]:
import copy
x = [11, 22, 33]
y = [44, 55, 66]
a = [ 1, 2, 3, x, y]

# b =a.copy()
b = copy.deepcopy(a)

b[0] = 100
b[3][0] = 200
print('a: ', a)
print('b: ', b)

a:  [1, 2, 3, [11, 22, 33], [44, 55, 66]]
b:  [100, 2, 3, [200, 22, 33], [44, 55, 66]]


In [5]:
d = {1: 1, "a": 45, 3: 3}
d.values()

dict_values([1, 45, 3])

In [40]:
def cycle(iterable):
    y=0
    while True:        
        for x in iterable:
            y+=x
            yield (x**2)/0.878979 + y**2

In [ ]:
a = [1, 2, 3]
inp = None
while True:
    inp = input("Enter a number (or 'q' to quit): ")
    if inp != "q":
        print(cycle(a))

<generator object cycle at 0x0000018C6CF207B0>


In [1]:
def cycle(iterable):  
    for x in iterable:
        yield x

In [41]:
gen = cycle([1, 2, 3])