In [1]:
import h5py
import numpy as np # Often used with h5py

# Define the path to your file
file_path = r'M:\Order to PC\CAD_Reconstruction\Generate_CAD\Decoder\data\cad_vec\0000\00001170.h5'
data = h5py.File(file_path, 'r') 



In [2]:
data.keys()

<KeysViewHDF5 ['vec']>

In [5]:
data["vec"]

<HDF5 dataset "vec": shape (10, 17), type "<i8">

In [17]:
data["vec"][:,0]

array([4, 0, 0, 0, 0, 0, 0, 0, 5, 3], dtype=int64)

In [35]:
for i in range(data['vec'].shape[0]):
    print(data['vec'][i])


[ 4 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[  0 209 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
[  0 209 126  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
[  0 223 126  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
[  0 223 133  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
[  0 218 139  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
[  0 128 139  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
[  0 128 128  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
[  5  -1  -1  -1  -1  -1 192 128 192 128 128 128  96 130 128   0   0]
[ 3 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
